# Generated by Django 3.2.6 on 2021-09-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoapp',
            name='bollen',
        ),
        migrations.AlterField(
            model_name='todoapp',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
